"""Slash command registry — single source of truth for all chat slash commands."""

from __future__ import annotations

import logging
from dataclasses import dataclass, field

logger = logging.getLogger("code_agents.chat.slash_registry")


@dataclass
class SlashEntry:
    help: str
    group: str  # "nav", "session", "agent", "ops", "config", "analysis", "tools"
    handler_module: str  # e.g. "chat_slash_nav"
    handler_func: str  # e.g. "_handle_navigation"
    aliases: list[str] = field(default_factory=list)


SLASH_REGISTRY: dict[str, SlashEntry] = {
    "/quit": SlashEntry(
        help="Exit chat (also /exit, /q, Ctrl+C)",
        group="nav",
        handler_module="chat_slash_nav",
        handler_func="_handle_navigation",
        aliases=["/exit", "/q", "/bye"],
    ),
    "/restart": SlashEntry(
        help="Restart chat / reconnect",
        group="nav",
        handler_module="chat_slash_nav",
        handler_func="_handle_navigation",
    ),
    "/help": SlashEntry(
        help="Show all chat commands",
        group="nav",
        handler_module="chat_slash_nav",
        handler_func="_handle_navigation",
    ),
    "/open": SlashEntry(
        help="Open related resource (browser / UI)",
        group="nav",
        handler_module="chat_slash_nav",
        handler_func="_handle_navigation",
    ),
    "/setup": SlashEntry(
        help="Run setup wizard from chat",
        group="nav",
        handler_module="chat_slash_nav",
        handler_func="_handle_navigation",
    ),
    "/session": SlashEntry(
        help="Show current session ID",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/clear": SlashEntry(
        help="Clear session, start fresh",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/history": SlashEntry(
        help="List saved sessions",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/resume": SlashEntry(
        help="Resume a saved session by id",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/delete-chat": SlashEntry(
        help="Delete a saved session",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/export": SlashEntry(
        help="Export conversation to markdown",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/agent": SlashEntry(
        help="Switch to another agent",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/agents": SlashEntry(
        help="List all agents with roles",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/rules": SlashEntry(
        help="Show active rules for current agent",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/skills": SlashEntry(
        help="List skills for an agent",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/tokens": SlashEntry(
        help="Token usage (session/daily/monthly)",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/stats": SlashEntry(
        help="Quick session stats",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/memory": SlashEntry(
        help="Show agent memory",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/run": SlashEntry(
        help="Run shell command in repo directory",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/execute", "/exec"],
    ),
    "/bash": SlashEntry(
        help="Direct shell execution",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/btw": SlashEntry(
        help="Side-message without interrupting the agent",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/repo": SlashEntry(
        help="Switch repos without restarting",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/endpoints": SlashEntry(
        help="Browse discovered API endpoints",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/superpower": SlashEntry(
        help="Auto-execute all safe commands",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/permissions": SlashEntry(
        help="View autorun rules, trusted commands, and permission modes",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/perms"],
    ),
    "/sandbox": SlashEntry(
        help="Restrict agent command writes to project dir (on|off|status)",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/layout": SlashEntry(
        help="Toggle fixed terminal input layout",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/voice": SlashEntry(
        help="Speech-to-text input",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/plan": SlashEntry(
        help="Create or manage execution plans",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/confirm": SlashEntry(
        help="Toggle requirement confirmation gate (on|off|show)",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/mcp": SlashEntry(
        help="MCP servers and tools",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/model": SlashEntry(
        help="Switch model mid-conversation",
        group="config",
        handler_module="chat_slash_config",
        handler_func="_handle_config",
    ),
    "/backend": SlashEntry(
        help="Switch backend (cursor, claude, claude-cli)",
        group="config",
        handler_module="chat_slash_config",
        handler_func="_handle_config",
    ),
    "/theme": SlashEntry(
        help="Switch color theme (dark, light, colorblind, ANSI)",
        group="config",
        handler_module="chat_slash_config",
        handler_func="_handle_config",
    ),
    "/investigate": SlashEntry(
        help="Search Kibana logs, correlate deploys",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/blame": SlashEntry(
        help="Deep git blame: PR, Jira, commit story",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/generate-tests": SlashEntry(
        help="AI-generate unit + integration tests for a file",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/refactor": SlashEntry(
        help="Code smells, refactoring suggestions, risk",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/deps": SlashEntry(
        help="Dependency tree: callers and callees",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/config-diff": SlashEntry(
        help="Compare configs across environments",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/flags": SlashEntry(
        help="Feature flags, env matrix, stale flags",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/pr-preview": SlashEntry(
        help="Preview a PR before opening it",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/impact": SlashEntry(
        help="Impact analysis: dependents, tests, risk",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/solve": SlashEntry(
        help="Structured problem decomposition",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/review-reply": SlashEntry(
        help="Replies to PR review comments",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/qa-suite": SlashEntry(
        help="QA regression suite generation",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/kb": SlashEntry(
        help="Search team knowledge base",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/pair": SlashEntry(
        help="Pair programming file watcher",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/coverage-boost": SlashEntry(
        help="Auto-boost test coverage",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/mutate": SlashEntry(
        help="Mutation testing — inject faults, verify tests catch them",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/mutate-test", "/mutation-test"],
    ),
    "/testdata": SlashEntry(
        help="Generate test data / fixtures",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/profile": SlashEntry(
        help="Performance profiler — cProfile hotspots and optimization suggestions",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/profiler", "/perf-profile"],
    ),
    "/compile": SlashEntry(
        help="Compile / syntax check",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/verify": SlashEntry(
        help="Toggle auto-verify with code-reviewer",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/style": SlashEntry(
        help="Code style detection for prompts",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/commands": SlashEntry(
        help="Interactive command browser — browse all CLI commands by category",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/cmds", "/cmd"],
    ),
    "/gen-tests": SlashEntry(
        help="AI test generation — auto-delegate to code-tester, write & verify",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/generate-tests", "/testgen"],
    ),
    "/watch": SlashEntry(
        help="Watch mode — auto-lint, auto-test, auto-fix on file save",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/slack": SlashEntry(
        help="Slack integration — test webhook, send message, status",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/bg": SlashEntry(
        help="Background agent manager — interactive task panel",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/tasks"],
    ),
    "/cost": SlashEntry(
        help="Token cost dashboard (today/daily/monthly/agent/model)",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
        aliases=["/costs", "/spend"],
    ),
    "/undo": SlashEntry(
        help="Undo last agent action (file edits, git commits)",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/rollback", "/revert"],
    ),
    "/diff-preview": SlashEntry(
        help="Toggle diff preview mode (on|off|status)",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/diffmode"],
    ),
    "/skill": SlashEntry(
        help="Skill marketplace: /skill list|search|install|remove|info",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/marketplace"],
    ),
    "/fg": SlashEntry(
        help="Bring background task to foreground: /fg [N]",
        group="ops",
        handler_module="chat_async_repl",
        handler_func="_handle_fg_command",
    ),
    # --- High-impact features ---
    "/debug": SlashEntry(
        help="Autonomous debug — reproduce, trace, root-cause, fix, verify",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
    ),
    "/review": SlashEntry(
        help="AI code review with inline diff — /review [--base main] [--fix] [--category security] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/benchmark": SlashEntry(
        help="Run agent benchmarks — quality & latency comparison",
        group="tools",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
        aliases=["/bench"],
    ),
    "/bench-compare": SlashEntry(
        help="Compare benchmark runs for regressions",
        group="tools",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
    ),
    "/bench-trend": SlashEntry(
        help="Show benchmark quality trend over time",
        group="tools",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
    ),
    "/branch": SlashEntry(
        help="Fork conversation at current point: /branch [name]",
        group="session",
        handler_module="chat_branch",
        handler_func="_handle_branch",
    ),
    "/branches": SlashEntry(
        help="List all conversation branches",
        group="session",
        handler_module="chat_branch",
        handler_func="_handle_branch",
    ),
    "/switch": SlashEntry(
        help="Switch to another conversation branch: /switch <name>",
        group="session",
        handler_module="chat_branch",
        handler_func="_handle_branch",
    ),
    "/merge": SlashEntry(
        help="Merge a branch into main: /merge <name>",
        group="session",
        handler_module="chat_branch",
        handler_func="_handle_branch",
    ),
    "/workspace": SlashEntry(
        help="Multi-repo workspace management",
        group="ops",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
        aliases=["/ws"],
    ),
    "/workspace-cross-deps": SlashEntry(
        help="Find cross-repo dependencies across workspace",
        group="ops",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
        aliases=["/cross-deps"],
    ),
    "/workspace-pr": SlashEntry(
        help="Create coordinated PRs across workspace repos",
        group="ops",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
        aliases=["/ws-pr"],
    ),
    "/pipeline": SlashEntry(
        help="Run agent pipelines — declarative agent chains",
        group="ops",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
        aliases=["/pipe"],
    ),
    "/share": SlashEntry(
        help="Live collaboration — share session with teammates",
        group="ops",
        handler_module="chat_slash_features",
        handler_func="_handle_features",
    ),
    # --- Productivity features ---
    "/pr-describe": SlashEntry(
        help="Generate PR description from branch diff",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
        aliases=["/pr-desc"],
    ),
    "/postmortem": SlashEntry(
        help="Generate incident postmortem from time range",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/postmortem-gen": SlashEntry(
        help="Auto-generate structured postmortem with timeline, root cause, impact",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
        aliases=["/pm-gen"],
    ),
    "/dep-upgrade": SlashEntry(
        help="Scan outdated dependencies",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/review-buddy": SlashEntry(
        help="Pre-push code review against conventions",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/db-migrate": SlashEntry(
        help="Generate DB migration from plain English",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
        aliases=["/migration"],
    ),
    "/oncall-summary": SlashEntry(
        help="Summarize on-call alerts + standup",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/test-impact": SlashEntry(
        help="Analyze impacted tests from changes",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/runbook": SlashEntry(
        help="Execute runbooks with safety gates",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/sprint-dashboard": SlashEntry(
        help="Sprint velocity + cycle time dashboard",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
        aliases=["/sprint-dash"],
    ),
    "/explain": SlashEntry(
        help="Ask questions about the codebase",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
    ),
    "/explain-code": SlashEntry(
        help="Explain a code block or function -- /explain-code <file>[:start-end] [--function <name>]",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/xplain"],
    ),
    "/corrections": SlashEntry(
        help="View or clear agent correction history",
        group="agent",
        handler_module="chat_slash_agents",
        handler_func="_handle_agent_ops",
    ),
    "/mindmap": SlashEntry(
        help="Generate visual mindmap of the repo (text/mermaid/html)",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/mind-map"],
    ),
    "/migrate-tracing": SlashEntry(
        help="Migrate legacy tracing to OpenTelemetry (scan/apply/rollback)",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/otel-migrate"],
    ),
    "/txn-flow": SlashEntry(
        help="Visualize transaction flow from logs or code (--from-code|--order-id)",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/transaction-flow"],
    ),
    "/dep-impact": SlashEntry(
        help="Dependency impact scanner — analyze upgrade risk: /dep-impact requests==3.0.0 [--check|--apply]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/impact"],
    ),
    "/pci-scan": SlashEntry(
        help="PCI-DSS compliance scanner — /pci-scan [--format text|json] [--severity critical|high|all]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/pci"],
    ),
    "/owasp-scan": SlashEntry(
        help="OWASP Top 10 scanner — /owasp-scan [--format text|json] [--severity critical|high|all]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/owasp"],
    ),
    "/replay": SlashEntry(
        help="Replay agent trace — /replay [show|play|fork|delete] <trace_id> [step_id]",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/traces": SlashEntry(
        help="List or search agent traces — /traces [search <query>]",
        group="session",
        handler_module="chat_slash_session",
        handler_func="_handle_session",
    ),
    "/idempotency": SlashEntry(
        help="Audit payment endpoints for idempotency key patterns [--severity critical|all] [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/idempotency-audit"],
    ),
    "/tail": SlashEntry(
        help="Live tail — stream logs with anomaly detection: /tail --service <name> [--env dev] [--level ERROR]",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/live-tail"],
    ),
    "/changelog": SlashEntry(
        help="Generate changelog with PR enrichment: /changelog <from>..<to> [--format markdown|terminal]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/validate-states": SlashEntry(
        help="Validate transaction state machines — /validate-states [--format text|json|mermaid]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/state-machine"],
    ),
    "/acquirer-health": SlashEntry(
        help="Monitor acquirer health — /acquirer-health [--env prod] [--window 1h] [--format text|json]",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/acq-health"],
    ),
    "/api-docs": SlashEntry(
        help="Automated API docs — scan routes, generate OpenAPI/Markdown/HTML: /api-docs [--format openapi|markdown|html] [--output file]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/apidocs"],
    ),
    "/translate": SlashEntry(
        help="Translate code between languages — /translate <file> --to <lang> [--output <path>]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/code-translate"],
    ),
    "/schema": SlashEntry(
        help="Database schema visualizer — /schema --sql-file schema.sql [--format terminal|mermaid|html]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/schema-viz", "/erd"],
    ),
    "/retry-audit": SlashEntry(
        help="Payment retry strategy analyzer — /retry-audit [--severity critical|all] [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/retry-scan"],
    ),
    "/dashboard": SlashEntry(
        help="Code health dashboard — tests, coverage, complexity, open PRs",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/health", "/health-dashboard"],
    ),
    "/recon": SlashEntry(
        help="Payment reconciliation debugger — /recon --orders orders.csv --settlements bank.csv [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/reconcile", "/recon-debug"],
    ),
    "/load-test": SlashEntry(
        help="Generate load test scripts — /load-test [--format k6|locust|jmeter] [--scenario smoke|peak|stress|soak]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/loadtest"],
    ),
    "/settlement": SlashEntry(
        help="Settlement file parser & validator — /settlement --file data.csv [--format visa|mastercard|upi|auto] [--compare bank.csv] [--output adj.csv]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/settle"],
    ),
    "/batch": SlashEntry(
        help="Batch operations — apply instruction across files: /batch --instruction \"add docstrings\" [--pattern *.py] [--dry-run]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/batch-ops"],
    ),
    # --- Missing slash wiring (CLI commands now accessible in chat) ---
    "/doctor": SlashEntry(
        help="Diagnose environment, integrations, and configuration",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/install-hooks": SlashEntry(
        help="Install AI-powered git hooks (pre-commit, pre-push)",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/hooks"],
    ),
    "/index": SlashEntry(
        help="Build/update RAG vector index for smart context — /index [--force] [--stats]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/rag-index"],
    ),
    "/tech-debt": SlashEntry(
        help="Deep tech debt scan — TODOs, complexity, test gaps, outdated deps, dead code: /tech-debt [--json] [--save]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/debt-scan", "/debt"],
    ),
    "/deadcode": SlashEntry(
        help="Find unreachable functions, unused classes, orphan files",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/dead-code"],
    ),
    "/dead-code-eliminate": SlashEntry(
        help="Cross-file dead code detection + safe removal: /dead-code-eliminate [--apply] [--dry-run]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/eliminate-dead", "/dce"],
    ),
    "/complexity": SlashEntry(
        help="Analyze cyclomatic complexity, find hotspots",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/security": SlashEntry(
        help="Run security scanner on codebase",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/security-scan"],
    ),
    "/coverage": SlashEntry(
        help="Show test coverage report",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
    ),
    "/env-health": SlashEntry(
        help="Check environment health — configs, integrations, connectivity",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/incident": SlashEntry(
        help="Start incident response workflow",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
    ),
    "/ci-heal": SlashEntry(
        help="CI pipeline self-healing — diagnose failure, apply fix, re-trigger",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/self-heal", "/ci-fix"],
    ),
    "/pr-respond": SlashEntry(
        help="Respond to PR review comments — address feedback, push fixes, reply in-thread",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/pr-thread"],
    ),
    "/screenshot": SlashEntry(
        help="Screenshot-to-code — generate UI from image or description: /screenshot --description 'login form' [--framework react|vue|html] [--output file]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/s2c", "/screenshot-to-code"],
    ),
    "/spec-validate": SlashEntry(
        help="Validate spec/PRD/Jira requirements against implementation — /spec-validate --spec <text>|--jira <key>|--prd <file>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/spec-check", "/validate-spec"],
    ),
    "/smell": SlashEntry(
        help="Code smell detector — /smell [target] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/code-smell", "/smells"],
    ),
    "/imports": SlashEntry(
        help="Import optimizer — /imports [target] [--fix] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/import-optimizer", "/optimize-imports"],
    ),
    "/adr": SlashEntry(
        help="Generate ADR — /adr --decision 'Use PostgreSQL' [--context '...'] [--alternatives '...']",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/decision"],
    ),
    "/clones": SlashEntry(
        help="Detect code clones — /clones [--threshold 0.8] [--min-tokens 50] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/clone-detect", "/duplicates"],
    ),
    "/naming-audit": SlashEntry(
        help="Audit naming conventions — /naming-audit [target] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/naming", "/name-check"],
    ),
    "/encryption-audit": SlashEntry(
        help="Encryption audit — /encryption-audit [--format text|json] [--severity critical|all]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/crypto-audit"],
    ),
    "/vuln-chain": SlashEntry(
        help="Vulnerability dep chain — /vuln-chain [--format text|json] [--severity critical|all]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/vuln-scan", "/dep-vuln"],
    ),
    "/input-audit": SlashEntry(
        help="Input validation coverage — /input-audit [--severity critical|all] [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/input-scan", "/validation-audit"],
    ),
    "/rate-limit-audit": SlashEntry(
        help="Audit endpoints for missing rate limiting — /rate-limit-audit [--severity critical|all] [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/rl-audit", "/ratelimit-audit"],
    ),
    "/privacy-scan": SlashEntry(
        help="Data privacy scanner — /privacy-scan [--regulation gdpr|dpdp|all] [--format text|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/privacy-audit", "/pii-scan"],
    ),
    "/compliance-report": SlashEntry(
        help="Compliance report — /compliance-report [--standard pci|soc2|gdpr] [--format text|markdown|json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/compliance", "/compliance-gen"],
    ),
    "/add-types": SlashEntry(
        help="Add type annotations to untyped functions — /add-types [--path src/] [--dry-run] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/type-adder"],
    ),
    "/comment-audit": SlashEntry(
        help="Audit comment quality — /comment-audit [target] [--json] [--category obvious|todo_no_ticket|commented_code|outdated]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/audit-comments"],
    ),
    "/secret-rotation": SlashEntry(
        help="Track secret rotation — /secret-rotation [--max-age 90] [--json] [--runbook]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/rotate-secrets"],
    ),
    "/acl-matrix": SlashEntry(
        help="Generate ACL matrix — /acl-matrix [--format text|json|markdown]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/acl"],
    ),
    "/session-audit": SlashEntry(
        help="Audit session management — /session-audit [--format text|json] [--severity critical|all]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/audit-sessions"],
    ),
    "/archaeology": SlashEntry(
        help="Code archaeology — trace origin and intent: /archaeology <file>[:line] [--function <name>]",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/archaeo", "/dig"],
    ),
    "/perf-proof": SlashEntry(
        help="Performance benchmark with proof — /perf-proof --command \"<cmd>\" [--iterations N]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/perf-bench"],
    ),
    "/contract-test": SlashEntry(
        help="Generate API contract tests — /contract-test [--format pact|schema|both] [--output dir]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/contract-tests", "/pact"],
    ),
    "/self-bench": SlashEntry(
        help="Self-benchmark agent quality — /self-bench [--tasks review,test,bug] [--trend] [--save]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/self-benchmark"],
    ),
    "/lang-migrate": SlashEntry(
        help="Migrate module to another language — /lang-migrate --source src/ --to go [--output dir]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/lang-migration"],
    ),
    "/preview": SlashEntry(
        help="Live preview server — /preview [--port 3333]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/live-preview"],
    ),
    "/full-audit": SlashEntry(
        help="Global audit orchestrator — run all scanners + quality gates: /full-audit [--quick] [--category security,payment] [--ci] [--gates-only] [--format terminal|json|html]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/audit-all", "/global-audit"],
    ),
    # --- Code Understanding Tools (Session 1) ---
    "/usage-trace": SlashEntry(
        help="Find all usages of a symbol: /usage-trace <symbol>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/trace", "/where-used"],
    ),
    "/nav": SlashEntry(
        help="Semantic codebase search: /nav <query>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/codebase-nav", "/search-code"],
    ),
    "/git-story": SlashEntry(
        help="Full story behind a line of code: /git-story <file> <line>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/code-story", "/blame-story"],
    ),
    "/call-chain": SlashEntry(
        help="Show call tree (callers + callees): /call-chain <function>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/callers", "/callees"],
    ),
    "/examples": SlashEntry(
        help="Find code examples for a concept: /examples <query>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/code-examples", "/show-usage"],
    ),
    "/dep-graph": SlashEntry(
        help="Dependency graph with visualization: /dep-graph <module> [--mermaid]",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/dependency-graph"],
    ),
    # --- Session 2: Debugging + Testing Tools ---
    "/stack-decode": SlashEntry(
        help="Decode stack trace — map to code, explain, fix: /stack-decode <paste trace>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/decode-stack", "/stacktrace"],
    ),
    "/log-analyze": SlashEntry(
        help="Analyze logs — correlate, timeline, root cause: /log-analyze <paste logs>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/analyze-logs"],
    ),
    "/env-diff": SlashEntry(
        help="Compare env configs: /env-diff dev staging [--json] [--list]",
        group="ops",
        handler_module="chat_slash_ops",
        handler_func="_handle_operations",
        aliases=["/envdiff"],
    ),
    "/leak-scan": SlashEntry(
        help="Scan for memory leak patterns: /leak-scan",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/memory-leak"],
    ),
    "/deadlock-scan": SlashEntry(
        help="Scan for concurrency hazards: /deadlock-scan",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/race-detect"],
    ),
    "/edge-cases": SlashEntry(
        help="Suggest edge cases for a function: /edge-cases <file:func>",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/suggest-tests"],
    ),
    "/mock-build": SlashEntry(
        help="Generate mock for a class: /mock-build <file:Class>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/generate-mock"],
    ),
    "/test-fix": SlashEntry(
        help="Diagnose and fix failing tests: /test-fix <paste output>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/fix-test"],
    ),
    "/integration-scaffold": SlashEntry(
        help="Generate docker-compose + test fixtures: /integration-scaffold postgres redis",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/scaffold"],
    ),
    # --- Snippet, Ownership, Velocity ---
    "/snippet": SlashEntry(
        help="Smart snippet library: /snippet search|save|list|delete|show",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/snippets"],
    ),
    "/ownership": SlashEntry(
        help="Code ownership analysis: /ownership [--generate-codeowners] [--silos] [--json]",
        group="analysis",
        handler_module="chat_slash_analysis",
        handler_func="_handle_analysis",
        aliases=["/codeowners"],
    ),
    "/velocity": SlashEntry(
        help="Sprint velocity prediction: /velocity [--committed N] [--json]",
        group="productivity",
        handler_module="chat_slash_productivity",
        handler_func="_handle_productivity",
        aliases=["/velocity-predict"],
    ),
    # --- Features 17-20: PR Split, License Audit, Config Validator, Release Notes ---
    "/pr-split": SlashEntry(
        help="Suggest how to split branch into smaller PRs: /pr-split [--base main] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/split-pr"],
    ),
    "/license-audit": SlashEntry(
        help="Audit dependency licenses for compliance: /license-audit [--sbom] [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/license-check"],
    ),
    "/validate-config": SlashEntry(
        help="Validate config files (YAML/JSON/TOML/.env): /validate-config [--json]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/config-validate"],
    ),
    "/release-notes": SlashEntry(
        help="Generate release notes from git history: /release-notes <from>..<to> [--format markdown|slack]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/relnotes"],
    ),
    # --- Feature 36-56: Testing, Browser, KB, Onboarding ---
    "/prop-test": SlashEntry(
        help="Generate Hypothesis property-based tests: /prop-test <file> [--function <name>]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/property-test", "/hypothesis"],
    ),
    "/test-style": SlashEntry(
        help="Analyze test style or generate matching tests: /test-style [--analyze] [--generate <file>]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/style-test"],
    ),
    "/visual-test": SlashEntry(
        help="Visual regression testing: /visual-test --url <url> [--compare] [--list]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/visual-regression"],
    ),
    "/browse": SlashEntry(
        help="Browser agent — fetch page, extract API docs: /browse --url <url> [--extract-api]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/browser"],
    ),
    "/team-kb": SlashEntry(
        help="Team knowledge base: /team-kb [list|add|get|search|delete] <topic>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/knowledge-base"],
    ),
    "/onboard-tour": SlashEntry(
        help="Generate onboarding tour for new developers",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/tour"],
    ),
    # --- Session 3: API + Database Tools ---
    "/endpoint-gen": SlashEntry(
        help="Generate CRUD endpoints: /endpoint-gen <Resource> [--framework fastapi|express|flask|django]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/gen-endpoint", "/crud-gen"],
    ),
    "/api-sync": SlashEntry(
        help="Check API spec/code sync: /api-sync <spec-file>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/spec-sync"],
    ),
    "/response-optimize": SlashEntry(
        help="Scan for response optimization: /response-optimize [--path src/]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/resp-opt"],
    ),
    "/rest-to-grpc": SlashEntry(
        help="Convert REST to gRPC proto: /rest-to-grpc [--output service.proto]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/grpc-gen", "/proto-gen"],
    ),
    "/api-changelog": SlashEntry(
        help="Diff API spec versions: /api-changelog <old-spec> <new-spec> [--format markdown]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/api-diff"],
    ),
    "/query-optimize": SlashEntry(
        help="Analyze SQL query: /query-optimize <query|file>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/sql-optimize"],
    ),
    "/schema-design": SlashEntry(
        help="Design DB schema from entities: /schema-design <entity-json|file>",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/design-schema"],
    ),
    "/orm-review": SlashEntry(
        help="Scan ORM for anti-patterns: /orm-review [--path src/models/]",
        group="tools",
        handler_module="chat_slash_tools",
        handler_func="_handle_tools",
        aliases=["/review-orm", "/orm-audit"],
    ),
}
