"""Setup env file management — parse, write, sections."""

from __future__ import annotations

import datetime
import logging
import os
import re
import shutil
from pathlib import Path

from .setup_ui import bold, green, yellow, red, dim, prompt_yes_no

logger = logging.getLogger("code_agents.setup.setup_env")

# ---------------------------------------------------------------------------
# Env file sections
# ---------------------------------------------------------------------------

_ENV_SECTIONS = [
    ("# Profile", ["CODE_AGENTS_NICKNAME", "CODE_AGENTS_USER_ROLE"]),
    ("# Core", ["CURSOR_API_KEY", "CURSOR_API_URL", "CODE_AGENTS_HTTP_ONLY",
                "CODE_AGENTS_LOCAL_LLM_URL", "CODE_AGENTS_LOCAL_LLM_API_KEY", "OLLAMA_API_KEY",
                "CODE_AGENTS_BACKEND", "CODE_AGENTS_CLAUDE_CLI_MODEL",
                "ANTHROPIC_API_KEY"]),
    ("# Server", ["HOST", "PORT", "LOG_LEVEL", "CODE_AGENTS_PUBLIC_BASE_URL", "OPEN_WEBUI_PUBLIC_URL"]),
    ("# Target Repository", ["TARGET_REPO_PATH", "TARGET_REPO_REMOTE"]),
    ("# Testing", ["TARGET_TEST_COMMAND", "TARGET_COVERAGE_THRESHOLD"]),
    ("# Jenkins", ["JENKINS_URL", "JENKINS_USERNAME", "JENKINS_API_TOKEN", "JENKINS_BUILD_JOB", "JENKINS_DEPLOY_JOB", "JENKINS_DEPLOY_JOB_DEV", "JENKINS_DEPLOY_JOB_QA"]),
    ("# ArgoCD", ["ARGOCD_URL", "ARGOCD_USERNAME", "ARGOCD_PASSWORD", "ARGOCD_APP_NAME", "ARGOCD_APP_PATTERN", "ARGOCD_VERIFY_SSL"]),
    ("# Elasticsearch", ["ELASTICSEARCH_URL", "ELASTICSEARCH_CLOUD_ID", "ELASTICSEARCH_API_KEY",
                         "ELASTICSEARCH_USERNAME", "ELASTICSEARCH_PASSWORD",
                         "ELASTICSEARCH_CA_CERTS", "ELASTICSEARCH_VERIFY_SSL"]),
    ("# Atlassian OAuth", ["ATLASSIAN_OAUTH_CLIENT_ID", "ATLASSIAN_OAUTH_CLIENT_SECRET",
                           "ATLASSIAN_OAUTH_SCOPES", "ATLASSIAN_CLOUD_SITE_URL",
                           "ATLASSIAN_OAUTH_SUCCESS_REDIRECT", "CODE_AGENTS_HTTPS_VERIFY"]),
    ("# Redash", ["REDASH_BASE_URL", "REDASH_API_KEY", "REDASH_USERNAME", "REDASH_PASSWORD"]),
]


def merged_config_for_cwd(cwd: str) -> dict[str, str]:
    """Merge config files in the same order as :func:`load_all_env` (later wins).

    Used by ``code-agents init`` for defaults and status — must match runtime.
    """
    from code_agents.core.env_loader import GLOBAL_ENV_PATH, PER_REPO_FILENAME, repo_config_path

    merged: dict[str, str] = {}
    if GLOBAL_ENV_PATH.is_file():
        merged.update(parse_env_file(GLOBAL_ENV_PATH))
    centralized = repo_config_path(cwd)
    if centralized.is_file():
        merged.update(parse_env_file(centralized))
    legacy_dotenv = Path(cwd) / ".env"
    if legacy_dotenv.is_file():
        merged.update(parse_env_file(legacy_dotenv))
    repo_legacy = Path(cwd) / PER_REPO_FILENAME
    if repo_legacy.is_file():
        merged.update(parse_env_file(repo_legacy))
    return merged


def parse_env_file(path: Path) -> dict[str, str]:
    """Parse a .env file into a dict."""
    result = {}
    if not path.exists() or not path.is_file():
        return result
    for line in path.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        match = re.match(r'^([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)', line)
        if match:
            key = match.group(1)
            value = match.group(2).strip()
            if len(value) >= 2 and value[0] == value[-1] and value[0] in ('"', "'"):
                value = value[1:-1]
            result[key] = value
    return result


def _write_env_to_path(
    env_path: Path,
    env_vars: dict[str, str],
    label: str,
    unset_keys: set[str] | None = None,
) -> None:
    """Write env vars to a specific path with section grouping."""
    env_path.parent.mkdir(parents=True, exist_ok=True)
    unset_keys = unset_keys or set()
    if not env_path.exists() and not env_vars:
        return

    if env_path.exists():
        existing = parse_env_file(env_path)
        existing_count = len(existing)
        # Auto-merge: preserve existing keys not in new vars, update those in new vars
        merged = dict(existing)
        removed = 0
        for k in unset_keys:
            if merged.pop(k, None) is not None:
                removed += 1
        added, updated = 0, 0
        for k, v in env_vars.items():
            if k not in merged:
                added += 1
            elif merged[k] != v:
                updated += 1
            merged[k] = v
        env_vars = merged
        if added or updated or removed:
            msg = f"{added} added, {updated} updated"
            if removed:
                msg += f", {removed} removed"
            print(dim(f"    Merged with existing {label}: {msg}, {existing_count - updated} unchanged."))

    lines = [f"# Generated by code-agents init — {label}", ""]
    written_keys: set[str] = set()

    for section_comment, keys in _ENV_SECTIONS:
        section_vars = {k: env_vars[k] for k in keys if k in env_vars}
        if section_vars:
            lines.append(section_comment)
            for k, v in section_vars.items():
                if '"' in v:
                    # Value contains double quotes — use single quotes
                    lines.append(f"{k}='{v}'")
                elif " " in v or "$" in v or "(" in v:
                    # Value has spaces or shell chars — use double quotes
                    lines.append(f'{k}="{v}"')
                else:
                    lines.append(f"{k}={v}")
                written_keys.add(k)
            lines.append("")

    remaining = {k: v for k, v in env_vars.items() if k not in written_keys}
    if remaining:
        lines.append("# Other")
        for k, v in remaining.items():
            if '"' in v:
                # Value contains double quotes — use single quotes
                lines.append(f"{k}='{v}'")
            elif " " in v or "$" in v or "(" in v:
                lines.append(f'{k}="{v}"')
            else:
                lines.append(f"{k}={v}")
        lines.append("")

    content = "\n".join(lines)
    env_path.write_text(content)

    try:
        os.chmod(env_path, 0o600)
    except OSError:
        pass

    count = len(env_vars)
    print(green(f"  ✓ {label} written ({count} variables, permissions: 600)"))
    print(f"    {dim(str(env_path))}")
    print()


def write_env_file(
    env_vars: dict[str, str],
    unset_keys: frozenset[str] | None = None,
) -> None:
    """Write env vars to centralized global + per-repo config files.

    Repo config is now stored at ~/.code-agents/repos/{repo-name}/config.env
    so no .env files clutter the actual project directory.

    ``unset_keys``: remove these keys from existing merged files (e.g. stale
    ``CODE_AGENTS_CLAUDE_CLI_MODEL`` after switching from Claude CLI to Cursor).
    """
    from code_agents.core.env_loader import (
        GLOBAL_ENV_PATH,
        PER_REPO_FILENAME,
        repo_config_path,
        split_unset_keys,
        split_vars,
    )

    unset_keys = unset_keys or frozenset()
    ug, ur = split_unset_keys(unset_keys)
    global_vars, repo_vars = split_vars(env_vars)

    if global_vars or ug:
        if global_vars:
            print(bold("  Writing global config (API keys, server, integrations):"))
        else:
            print(bold("  Updating global config (removing obsolete keys):"))
        _write_env_to_path(GLOBAL_ENV_PATH, global_vars, "global config", unset_keys=ug)

    if repo_vars or ur:
        # Write to centralized location: ~/.code-agents/repos/{repo-name}/config.env
        cwd = os.getcwd()
        centralized_path = repo_config_path(cwd)
        if repo_vars:
            print(bold(f"  Writing per-repo config to: {centralized_path}"))
        else:
            print(bold(f"  Updating per-repo config (removing obsolete keys): {centralized_path}"))
        _write_env_to_path(centralized_path, repo_vars, "repo config", unset_keys=ur)

        # If legacy .env.code-agents exists in repo, offer to migrate
        legacy_path = Path(cwd) / PER_REPO_FILENAME
        if legacy_path.is_file():
            print(dim(f"  Legacy {PER_REPO_FILENAME} found in repo directory."))
            print(dim(f"  Config is now centralized at: {centralized_path}"))
            print(dim(f"  You can safely delete: {legacy_path}"))
