"""Property-Based Test Synthesis — generate Hypothesis property tests from source code.

Analyzes function signatures (parameters + return types) and generates property-based
tests using Hypothesis strategies. Infers strategies from type annotations, detects
common properties (roundtrip, idempotent, no-crash), and outputs ready-to-run test code.

Usage::

    from code_agents.testing.property_tests import PropertyTestGenerator

    gen = PropertyTestGenerator("/path/to/repo")
    test_code = gen.generate("src/utils.py", function="encode")
"""

from __future__ import annotations

import ast
import logging
import os
import re
import textwrap
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger("code_agents.testing.property_tests")

# ---------------------------------------------------------------------------
# Type -> Hypothesis strategy mapping
# ---------------------------------------------------------------------------

_TYPE_STRATEGY_MAP: dict[str, str] = {
    "int": "st.integers()",
    "float": "st.floats(allow_nan=False, allow_infinity=False)",
    "str": "st.text(min_size=0, max_size=100)",
    "bytes": "st.binary(min_size=0, max_size=100)",
    "bool": "st.booleans()",
    "list": "st.lists(st.integers(), max_size=20)",
    "dict": "st.dictionaries(st.text(max_size=10), st.integers(), max_size=10)",
    "set": "st.sets(st.integers(), max_size=20)",
    "tuple": "st.tuples(st.integers(), st.integers())",
    "Optional[int]": "st.one_of(st.none(), st.integers())",
    "Optional[str]": "st.one_of(st.none(), st.text(max_size=50))",
    "Optional[float]": "st.one_of(st.none(), st.floats(allow_nan=False))",
    "Any": "st.one_of(st.integers(), st.text(max_size=20), st.booleans())",
    "None": "st.just(None)",
}

# Patterns for list[T], dict[K,V], etc.
_GENERIC_RE = re.compile(r"^(list|List)\[(\w+)\]$")
_DICT_RE = re.compile(r"^(dict|Dict)\[(\w+),\s*(\w+)\]$")
_OPTIONAL_RE = re.compile(r"^Optional\[(\w+)\]$")
_SET_RE = re.compile(r"^(set|Set)\[(\w+)\]$")


# ---------------------------------------------------------------------------
# Parsed function info
# ---------------------------------------------------------------------------

@dataclass
class FuncParam:
    """A single function parameter."""
    name: str
    annotation: str = ""
    default: str = ""


@dataclass
class FuncInfo:
    """Parsed function metadata."""
    name: str
    params: list[FuncParam] = field(default_factory=list)
    return_type: str = ""
    docstring: str = ""
    is_method: bool = False
    decorators: list[str] = field(default_factory=list)


# ---------------------------------------------------------------------------
# PropertyTestGenerator
# ---------------------------------------------------------------------------

class PropertyTestGenerator:
    """Generate Hypothesis property-based tests from source code."""

    def __init__(self, cwd: str) -> None:
        self.cwd = cwd
        logger.debug("PropertyTestGenerator initialized for %s", cwd)

    def generate(self, file_path: str, function: str = "") -> str:
        """Generate property tests for functions in a file.

        Args:
            file_path: Path to the Python source file (relative or absolute).
            function: Optional specific function name. If empty, generates for all.

        Returns:
            Generated test code as a string.
        """
        abs_path = self._resolve_path(file_path)
        if not os.path.isfile(abs_path):
            logger.warning("File not found: %s", abs_path)
            return f"# Error: file not found: {abs_path}"

        source = Path(abs_path).read_text(encoding="utf-8")
        functions = self._parse_functions(source)

        if function:
            functions = [f for f in functions if f.name == function]
            if not functions:
                return f"# Error: function '{function}' not found in {file_path}"

        if not functions:
            return f"# No functions found in {file_path}"

        # Build module import path
        module_path = self._file_to_module(file_path)

        lines: list[str] = []
        lines.append('"""Property-based tests generated by code-agents."""')
        lines.append("")
        lines.append("from hypothesis import given, assume, settings")
        lines.append("from hypothesis import strategies as st")
        lines.append("import pytest")
        lines.append("")

        if module_path:
            func_names = ", ".join(f.name for f in functions if not f.is_method)
            if func_names:
                lines.append(f"from {module_path} import {func_names}")
                lines.append("")

        for func in functions:
            if func.is_method:
                lines.append(f"# Skipping method: {func.name} (requires class instance)")
                lines.append("")
                continue

            test_code = self._generate_hypothesis_test(func.name, func.params, func.return_type)
            lines.append(test_code)
            lines.append("")

            # Add common property tests
            for prop_test in self._common_properties(func.name):
                lines.append(prop_test)
                lines.append("")

        result = "\n".join(lines)
        logger.info("Generated property tests for %d functions from %s", len(functions), file_path)
        return result

    def _infer_strategies(self, params: list[FuncParam]) -> dict[str, str]:
        """Map each parameter to a Hypothesis strategy based on its type annotation."""
        strategies: dict[str, str] = {}
        for p in params:
            if p.name in ("self", "cls"):
                continue
            ann = p.annotation.strip() if p.annotation else ""
            strategies[p.name] = self._type_to_strategy(ann)
        return strategies

    def _type_to_strategy(self, type_str: str) -> str:
        """Convert a type annotation string to a Hypothesis strategy."""
        if not type_str:
            # No annotation — default to a broad strategy
            return "st.one_of(st.integers(), st.text(max_size=20), st.booleans())"

        # Direct match
        if type_str in _TYPE_STRATEGY_MAP:
            return _TYPE_STRATEGY_MAP[type_str]

        # Optional[X]
        m = _OPTIONAL_RE.match(type_str)
        if m:
            inner = self._type_to_strategy(m.group(1))
            return f"st.one_of(st.none(), {inner})"

        # list[X]
        m = _GENERIC_RE.match(type_str)
        if m:
            elem = self._type_to_strategy(m.group(2))
            return f"st.lists({elem}, max_size=20)"

        # set[X]
        m = _SET_RE.match(type_str)
        if m:
            elem = self._type_to_strategy(m.group(2))
            return f"st.sets({elem}, max_size=20)"

        # dict[K, V]
        m = _DICT_RE.match(type_str)
        if m:
            key_st = self._type_to_strategy(m.group(2))
            val_st = self._type_to_strategy(m.group(3))
            return f"st.dictionaries({key_st}, {val_st}, max_size=10)"

        # Fallback
        logger.debug("Unknown type annotation: %s — using broad strategy", type_str)
        return "st.one_of(st.integers(), st.text(max_size=20))"

    def _generate_hypothesis_test(
        self, func_name: str, params: list[FuncParam], return_type: str,
    ) -> str:
        """Generate a single Hypothesis test function for a given function."""
        strategies = self._infer_strategies(params)

        if not strategies:
            # No parameters (or only self/cls)
            return textwrap.dedent(f"""\
                def test_{func_name}_no_crash():
                    \"\"\"Property: {func_name}() does not crash.\"\"\"
                    result = {func_name}()
                    assert result is not None or result is None  # no crash""")

        # Build @given decorator
        given_args = ", ".join(f"{k}={v}" for k, v in strategies.items())
        param_names = ", ".join(strategies.keys())

        lines = []
        lines.append(f"@given({given_args})")
        lines.append(f"@settings(max_examples=50)")
        lines.append(f"def test_{func_name}_no_crash({param_names}):")
        lines.append(f'    """Property: {func_name} does not crash on valid input."""')
        lines.append(f"    result = {func_name}({param_names})")

        # Add return type assertion if known
        if return_type and return_type != "None":
            py_type = return_type.replace("Optional[", "").replace("]", "")
            if py_type in ("int", "float", "str", "bool", "list", "dict", "set", "bytes"):
                lines.append(f"    assert isinstance(result, ({py_type}, type(None)))")

        return "\n".join(lines)

    def _common_properties(self, func_name: str) -> list[str]:
        """Generate common property tests: roundtrip, idempotent, no-crash.

        Returns a list of test function strings.
        """
        properties: list[str] = []

        # Idempotent check (for functions named with idempotent-like patterns)
        idem_patterns = ("normalize", "clean", "strip", "trim", "format", "sort", "unique", "dedup")
        if any(pat in func_name.lower() for pat in idem_patterns):
            properties.append(textwrap.dedent(f"""\
                @given(data=st.text(max_size=100))
                @settings(max_examples=30)
                def test_{func_name}_idempotent(data):
                    \"\"\"Property: applying {func_name} twice gives the same result.\"\"\"
                    once = {func_name}(data)
                    twice = {func_name}(once)
                    assert once == twice"""))

        # Roundtrip check (for encode/decode, serialize/deserialize pairs)
        roundtrip_pairs = {
            "encode": "decode",
            "serialize": "deserialize",
            "compress": "decompress",
            "encrypt": "decrypt",
            "to_json": "from_json",
            "to_dict": "from_dict",
            "pack": "unpack",
        }
        for fwd, rev in roundtrip_pairs.items():
            if func_name.lower().endswith(fwd) or func_name.lower() == fwd:
                properties.append(textwrap.dedent(f"""\
                    # NOTE: Roundtrip test — requires '{rev}' to be available
                    # @given(data=st.text(max_size=100))
                    # def test_{func_name}_roundtrip(data):
                    #     assert {rev}({func_name}(data)) == data"""))
                break

        return properties

    # --- Helpers ---

    def _resolve_path(self, file_path: str) -> str:
        """Resolve file path relative to cwd."""
        if os.path.isabs(file_path):
            return file_path
        return os.path.join(self.cwd, file_path)

    def _file_to_module(self, file_path: str) -> str:
        """Convert file path to Python module path (best-effort)."""
        # Strip .py extension
        p = file_path.replace(".py", "").replace("/", ".").replace("\\", ".")
        # Remove leading dots
        p = p.lstrip(".")
        # Remove 'src.' prefix if present
        if p.startswith("src."):
            p = p[4:]
        return p

    def _parse_functions(self, source: str) -> list[FuncInfo]:
        """Parse function signatures from Python source code using AST."""
        try:
            tree = ast.parse(source)
        except SyntaxError as e:
            logger.warning("Failed to parse source: %s", e)
            return []

        functions: list[FuncInfo] = []

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue

            # Skip private/dunder
            if node.name.startswith("_") and not node.name.startswith("__"):
                continue

            params: list[FuncParam] = []
            for arg in node.args.args:
                ann = ""
                if arg.annotation:
                    ann = ast.unparse(arg.annotation) if hasattr(ast, "unparse") else ""
                params.append(FuncParam(name=arg.arg, annotation=ann))

            return_type = ""
            if node.returns:
                return_type = ast.unparse(node.returns) if hasattr(ast, "unparse") else ""

            docstring = ast.get_docstring(node) or ""
            is_method = any(p.name == "self" for p in params)
            decorators = []
            for dec in node.decorator_list:
                if isinstance(dec, ast.Name):
                    decorators.append(dec.id)
                elif isinstance(dec, ast.Attribute):
                    decorators.append(ast.unparse(dec) if hasattr(ast, "unparse") else "")

            functions.append(FuncInfo(
                name=node.name,
                params=params,
                return_type=return_type,
                docstring=docstring,
                is_method=is_method,
                decorators=decorators,
            ))

        logger.debug("Parsed %d functions", len(functions))
        return functions
